<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>3itx</AssemblyName>
    <RootNamespace>_3itx_launcher</RootNamespace>
    <Version>1.0.5</Version>
    <AssemblyVersion>1.0.5.0</AssemblyVersion>
    <FileVersion>1.0.5.0</FileVersion>
    <ApplicationIcon>synz.ico</ApplicationIcon>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="*" />
    <PackageReference Include="System.Drawing.Common" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\init.lua">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\loading.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ExplorerIcons.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\JetBrainsMono-Regular.ttf" />
    <Resource Include="Fonts\JetBrainsMono-Medium.ttf" />
    <Resource Include="Fonts\JetBrainsMono-SemiBold.ttf" />
    <Resource Include="Fonts\JetBrainsMono-Bold.ttf" />
  </ItemGroup>

</Project>
